### OracleDB connection settings
spring:
  datasource:
#    url: 'jdbc:oracle:thin:@192.168.0.119:49154:ORCLCDB'
    url: 'jdbc:oracle:thin:@oracledb:1521:ORCLCDB'
    username: cypriiz
    password: cypriiz
    driver:
      class-name: 'oracle.jdbc.OracleDriver'

### Gmail connection setting
  mail:
    host: smtp.gmail.com
    username: coffeetimeneoflex@gmail.com
    password: neoflex123
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
